# docker-simplesamlphp

Docker image for Drupal 7 + simpleSAMLphp (SSP) with cookbook to configure an SP in a federation 


## Features

- simpleSAMLphp
** Install SSP from Github repo
** Immutable container, exposing config, log etc. to docker host volumes, with proper
   initialization from default values (using the scripts in the dscript folder)
** Run container as non-root
** Delegate TSL configuration to a dedicated proxy
** Using original templates from simpleSAMLphp except config-metarefresh.php
** Guidance for configuration with automated metadata source (federation setup)  
- Drupal
** Delegate TSL configuration to a dedicated proxy
** install simpleSAMLphp_auth module

## Prerequisites

  - Install [Docker](https://www.docker.com/)
  - Scripts in dscripts subproject work on Redhat and Debian Docker hosts, others need
    to be adapted

## Install Docker Build Environment

    git clone https://github.com/identinetics/docker-simplesamlphp.git
    cd docker-simplesamlphp
    git submodule update --init && cd dscripts && git checkout master && cd ..
    cp conf.sh.default conf.sh
    
    
Modify conf.sh to your local needs, then:
    
    dscripts/build.sh    
    
== Configuration

Link:doc/config_ssp.html[Configure SSP as an SAML2 SP]

Link:doc/config_d7.html[Configure Drupal7]
